pipeline {
    agent any
    stages {
        stage('Clean') {
        	steps {
        		bat 'cd Section-04c-01_JavaTutorial_MavenProject'
	           	bat 'mvn clean' 
	        }
           
        }
        stage('Test') {
        	steps {
	            bat 'mvn test' 
	        }
          
        }
        stage('Package') {
        	steps {
	            bat 'mvn package'
	        }
           
        }
    }
}