pipeline {
    agent any
    environment {
    	def pom = readMavenPom file: 'Section-04c-01_JavaTutorial_MavenProject\\pom.xml'
    }
    stages {
        stage('Clean') {
        	steps {
	           	bat 'mvn -f Section-04c-01_JavaTutorial_MavenProject clean'
	        }
           
        }
        stage('Test') {
        	steps {
	            bat 'mvn test' 
	        }
          
        }
        stage('Package') {
        	steps {
	            bat 'mvn package'
	        }
           
        }
    }
}